project_name: filebrowser

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

build:
  env:
    - CGO_ENABLED=0
  main: main.go
  binary: releasertest
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
    - dragonfly
    - solaris
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
    - goos: openbsd
      goarch: arm
    - goos: freebsd
      goarch: arm
    - goos: netbsd
      goarch: arm
    - goos: solaris
      goarch: arm

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  -
    dockerfile: Dockerfile
    binary: releasertest
    goos: linux
    goarch: amd64
    goarm: ''
    image_templates:
      - "o1egl/releasertest:latest"
      - "o1egl/releasertest:{{ .Tag }}"
      - "o1egl/releasertest:v{{ .Major }}"
  -
    dockerfile: Dockerfile
    binaries:
      - releasertest
    goos: linux
    goarch: arm
    goarm: '5'
    image_templates:
      - "o1egl/releasertest:pi"
      - "o1egl/releasertest:{{ .Tag }}-pi"
      - "o1egl/releasertest:v{{ .Major }}-pi"
